# Hospital Cleaning Notebook
This notebook implements the requested cleaning pipeline, creates the plots in the same notebook, and saves `hospital_cleaned.csv`.
Each code cell includes comments describing its purpose.

In [5]:
# Module 2: Data Cleaning & Transformation
## Hospital Operations & Patient Analytics Dashboard

In [6]:
import pandas as pd
import numpy as np

In [ ]:
## Load Dataset

In [7]:
df = pd.read_csv("hospital_raw_data.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [ ]:
## Dataset Overview

In [8]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])
print("Shape :", df.shape)

Rows : 10000
Columns : 61
Shape : (10000, 61)

In [9]:
df.head()

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag,Doctor Experience (Years),Patient Satisfaction Score,Ward Type,Follow-up Required,Payment Status,Discharge Status
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,43.0,0,0,0,3,3.4,General,No,Paid,Recovered
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,49.4,0,0,0,24,4.3,General,No,Paid,Recovered
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,30.7,0,0,1,20,4.5,General,No,Paid,Recovered
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,28.5,0,1,0,14,3.3,Private,No,Insurance,Recovered
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Icu,DEPT009,Dr. Priya Reddy,34,116,...,20.1,0,0,1,13,3.1,Semi-Private,No,Paid,Recovered

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 61 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hospital ID                     10000 non-null  object
 1   Hospital Name                   10000 non-null  object
 2   Hospital Type                   10000 non-null  object
 3   City                            10000 non-null  object
 4   State                           10000 non-null  object
 5   Department                      10000 non-null  object
 6   Department ID                   10000 non-null  object
 7   Doctor                          10000 non-null  object
 8   Nurses                          10000 non-null  int64
 9   Staff Count                     10000 non-null  int64
 10  Patient ID                      10000 non-null  object
 11  Patient Name                    10000 non-null  object
 12  Gender                          10000 non-null  object
 13  Age                             10000 non-null  int64
 14  Admission Date                  10000 non-null  object
 15  Discharge Date                  10000 non-null  object
 16  Diagnosis                       10000 non-null  object
 17  Treatment                       10000 non-null  object
 18  Medication                      10000 non-null  object
 19  Admission Type                  10000 non-null  object
 20  Test Result                     10000 non-null  object
 21  Blood Type                      10000 non-null  object
 22  Beds Available                  10000 non-null  int64
 23  ICU Beds                        10000 non-null  int64
 24  Bed Number                      10000 non-null  int64
 25  Bed Occupied                    10000 non-null  object
 26  Equipment                       10000 non-null  object
 27  Length of Stay                  10000 non-null  int64
 28  Room No                         10000 non-null  int64
 29  Billing Amount                  10000 non-null  int64
 30  Insurance Provider              10000 non-null  object
 31  Readmission                     10000 non-null  object
 32  Dept_Bed_Capacity_Derived       10000 non-null  int64
 33  Beds_Occupied_Count             10000 non-null  int64
 34  Equipment ID                    10000 non-null  object
 35  Equipment Number                10000 non-null  object
 36  Equipment Status                10000 non-null  object
 37  Equipment_Total_Inventory       10000 non-null  int64
 38  Equipment_Usage_Duration_Hours  10000 non-null  float64
 39  Transferred                     10000 non-null  object
 40  Transfer_From_Department        10000 non-null  object
 41  Transfer_To_Department          10000 non-null  object
 42  Transfer_Date                   1760 non-null   object
 43  Number_of_Transfers             10000 non-null  int64
 44  Dept_ICU_Bed_Capacity_Derived   10000 non-null  int64
 45  Dept_Staff_Capacity_Derived     10000 non-null  int64
 46  Admissions_Rate_%_Derived       10000 non-null  float64
 47  Staff_Utilization_%_Derived     10000 non-null  float64
 48  Bed_Occupancy_Rate_%            10000 non-null  float64
 49  Bed_Occupancy_Rate_Calc         10000 non-null  float64
 50  ICU_Occupancy_Rate_Calc         10000 non-null  float64
 51  Staff_Utilization_Calc          10000 non-null  float64
 52  Readmission_Flag                10000 non-null  int64
 53  Transferred_Flag                10000 non-null  int64
 54  Equipment_InUse_Flag            10000 non-null  int64
 55  Doctor Experience (Years)       10000 non-null  int64
 56  Patient Satisfaction Score      10000 non-null  float64
 57  Ward Type                       10000 non-null  object
 58  Follow-up Required              10000 non-null  object
 59  Payment Status                  10000 non-null  object
 60  Discharge Status                10000 non-null  object
dtypes: float64(8), int64(19), object(34)
memory usage: 4.7+ MB

In [12]:
## Dataset Statistics

In [13]:
df.describe(include='all')

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag,Doctor Experience (Years),Patient Satisfaction Score,Ward Type,Follow-up Required,Payment Status,Discharge Status
count,10000,10000,10000,10000,10000,10000,10000,10000,10000.00000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000,10000,10000,10000
unique,20,20,2,6,6,10,10,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,2,3,3
top,HOSP00012,Medindia Hospital,Private,Chennai,Tamil Nadu,Neurology,DEPT002,Dr. Rahul Verma,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,General,No,Paid,Recovered
freq,532,532,8496,1706,1706,1033,1033,2556,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3958,6522,4435,8269
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.53610,341.421000,...,57.924860,0.498700,0.176000,0.335500,15.39290,4.000110,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.24947,149.201603,...,25.296697,0.500023,0.380839,0.472189,8.61157,0.575849,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00000,80.000000,...,13.300000,0.000000,0.000000,0.000000,1.00000,3.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00000,214.750000,...,36.375000,0.000000,0.000000,0.000000,8.00000,3.500000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.00000,343.000000,...,58.200000,0.000000,0.000000,0.000000,15.00000,4.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.00000,470.000000,...,79.600000,1.000000,0.000000,1.000000,23.00000,4.500000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00000,600.000000,...,100.000000,1.000000,1.000000,1.000000,30.00000,5.000000,NaN,NaN,NaN,NaN

In [ ]:
## Check Missing Values

In [14]:
missing_values = df.isnull().sum()

print("Missing Values in Each Column")
print(missing_values)

Missing Values in Each Column
Hospital ID                   0
Hospital Name                 0
Hospital Type                 0
City                          0
State                         0
                             ..
Patient Satisfaction Score    0
Ward Type                     0
Follow-up Required            0
Payment Status                0
Discharge Status              0
Length: 61, dtype: int64

In [15]:
df = df.fillna({
    "Age": df["Age"].median(),
    "Gender": df["Gender"].mode()[0],
    "Department": df["Department"].mode()[0]
})

In [16]:
print(df.isnull().sum())

Hospital ID                   0
Hospital Name                 0
Hospital Type                 0
City                          0
State                         0
                             ..
Patient Satisfaction Score    0
Ward Type                     0
Follow-up Required            0
Payment Status                0
Discharge Status              0
Length: 61, dtype: int64

In [ ]:
## Check Duplicate Records

In [17]:
duplicate_records = df.duplicated().sum()

print("Duplicate Records :", duplicate_records)

Duplicate Records : 0

In [ ]:
## Remove Duplicate Records

In [18]:
df.drop_duplicates(inplace=True)

print("Duplicate records removed successfully.")

Duplicate records removed successfully.

In [ ]:
## Standardize Department Names

In [19]:
df["Department"] = df["Department"].str.strip().str.title()

print(df["Department"].unique())

['General Medicine' 'General Surgery' 'Pulmonology' 'Icu' 'Oncology'
 'Neurology' 'Orthopedics' 'Cardiology' 'Nephrology' 'Psychiatry']

In [23]:
## Validate Cleaned Dataset

In [24]:
print("Rows :", df.shape[0])

print("Columns :", df.shape[1])

print("Missing Values")

print(df.isnull().sum())

print()

print("Duplicate Records :", df.duplicated().sum())

Rows : 10000
Columns : 61
Missing Values
Hospital ID                   0
Hospital Name                 0
Hospital Type                 0
City                          0
State                         0
                             ..
Patient Satisfaction Score    0
Ward Type                     0
Follow-up Required            0
Payment Status                0
Discharge Status              0
Length: 61, dtype: int64

Duplicate Records : 0

In [ ]:
## Export Cleaned Dataset

In [25]:
df.to_csv("hospital_cleaned.csv", index=False)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

In [26]:
df.head()

,Hospital ID,Hospital Name,Hospital Type,City,State,Department,Department ID,Doctor,Nurses,Staff Count,...,Staff_Utilization_Calc,Readmission_Flag,Transferred_Flag,Equipment_InUse_Flag,Doctor Experience (Years),Patient Satisfaction Score,Ward Type,Follow-up Required,Payment Status,Discharge Status
0,HOSP00016,C K Hospital,Private,Mumbai,Maharashtra,General Medicine,DEPT004,Dr. Arjun Sharma,12,257,...,43.0,0,0,0,3,3.4,General,No,Paid,Recovered
1,HOSP00019,Cure Well Hospital,Private,Bengaluru,Karnataka,General Surgery,DEPT010,Dr. Sneha Rao,15,288,...,49.4,0,0,0,24,4.3,General,No,Paid,Recovered
2,HOSP00004,Yashoda Hospital,Private,Hyderabad,Telangana,Pulmonology,DEPT005,Dr. Priya Reddy,20,181,...,30.7,0,0,1,20,4.5,General,No,Paid,Recovered
3,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Pulmonology,DEPT005,Dr. Rahul Verma,23,170,...,28.5,0,1,0,14,3.3,Private,No,Insurance,Recovered
4,HOSP00017,Dharma Hospital,Private,Delhi,Delhi,Icu,DEPT009,Dr. Priya Reddy,34,116,...,20.1,0,0,1,13,3.1,Semi-Private,No,Paid,Recovered