In [ ]:
import os      # Import the os module to interact with the operating system
print(os.getcwd()) # Display the current working directory
print(os.listdir()) # Display all files and folders in the current directory

C:\Users\pranv\OneDrive\Desktop\Hospital Operations & Patient Analytics\Hospital-Operations-Patient-Analytics-\scripts
['.ipynb_checkpoints', 'data_collection.ipynb']

In [ ]:
import pandas as pd

df = pd.read_csv('../data/healthcare_dataset.csv') # Load the healthcare dataset
print(df.shape)
df.head()

(55500, 15)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [ ]:
condition_to_dept = {
    'Diabetes': 'Endocrinology',
    'Cancer': 'Oncology',                        
    'Obesity': 'General Medicine',
    'Asthma': 'Pulmonology',
    'Hypertension': 'Cardiology',
    'Arthritis': 'Orthopedics'
}# Map each medical condition to its corresponding department
 # Create a new Department column
df['Department'] = df['Medical Condition'].map(condition_to_dept)  
df[['Medical Condition', 'Department']].head(10)

  Medical Condition        Department
0            Cancer          Oncology
1           Obesity  General Medicine
2           Obesity  General Medicine
3          Diabetes     Endocrinology
4            Cancer          Oncology
5            Asthma       Pulmonology
6          Diabetes     Endocrinology
7            Cancer          Oncology
8            Asthma       Pulmonology
9            Cancer          Oncology

In [ ]:
departments = df['Department'].unique()
print(departments)
                                       # Create hospital resource data and merge it with the dataset
resource_data = pd.DataFrame({
    'Department': departments,
    'total_beds': [50, 60, 30, 40, 20, 35][:len(departments)],
    'staff_count': [20, 25, 15, 22, 30, 18][:len(departments)]
})
        # Merge patient data with department resource information
hospital_raw_data = pd.merge(df, resource_data, on='Department', how='left')
print(hospital_raw_data.shape)
hospital_raw_data.head()

['Oncology' 'General Medicine' 'Endocrinology' 'Pulmonology' 'Cardiology'
 'Orthopedics']
(55500, 18)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Department,total_beds,staff_count
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,Oncology,50,20
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,General Medicine,60,25
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,General Medicine,60,25
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,Endocrinology,30,15
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,Oncology,50,20

In [ ]:
print(len(hospital_raw_data))  # Display the total number of records in the dataset

55500

In [ ]:
completeness = (1 - hospital_raw_data.isnull().sum().sum() / hospital_raw_data.size) * 100
print(f"Dataset completeness: {completeness:.2f}%")     # Calculate the percentage of complete (non-missing) data

Dataset completeness: 100.00%

In [ ]:
hospital_raw_data.to_csv('../data/hospital_raw_data.csv', index=False) # Save the processed dataset as a CSV file
print("Saved successfully: hospital_raw_data.csv") # Display a confirmation message after saving the file

Saved successfully: hospital_raw_data.csv

In [ ]:
import pandas as pd

def load_data():
    df = pd.read_csv('../data/healthcare_dataset.csv')
    return df

def add_department(df):
    condition_to_dept = {
        'Diabetes': 'Endocrinology',
        'Cancer': 'Oncology',
        'Obesity': 'General Medicine',
        'Asthma': 'Pulmonology',
        'Hypertension': 'Cardiology',
        'Arthritis': 'Orthopedics'
    }
    df['Department'] = df['Medical Condition'].map(condition_to_dept)
    return df

def add_resources(df):
    departments = df['Department'].unique()
    resource_data = pd.DataFrame({
        'Department': departments,
        'total_beds': [50, 60, 30, 40, 20, 35][:len(departments)],
        'staff_count': [20, 25, 15, 22, 30, 18][:len(departments)]
    })
    merged = pd.merge(df, resource_data, on='Department', how='left')
    return merged

def main():
    df = load_data()
    df = add_department(df)
    df = add_resources(df)
    df.to_csv('../data/hospital_raw_data.csv', index=False)
    completeness = (1 - df.isnull().sum().sum() / df.size) * 100
    print(f"Saved: hospital_raw_data.csv | Shape: {df.shape} | Completeness: {completeness:.2f}%")

if __name__ == "__main__":
    main()

Saved: hospital_raw_data.csv | Shape: (55500, 18) | Completeness: 100.00%